version: "3.9"

services:
    ellegia-web-api:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - ellegia-ms-sql-server
    ellegia-ms-sql-server:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "SamplePassword123"
            ACCEPT_EULA: "Y"